# Generated by Django 3.1.2 on 2020-12-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('addr', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip_code', models.TextField()),
                ('card_number', models.IntegerField()),
                ('exp_date', models.TextField()),
                ('ccv', models.IntegerField()),
                ('product_id', models.TextField()),
                ('shoe_size', models.FloatField()),
            ],
        ),
    ]
